services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: auauth
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./drizzle:/migrations


volumes:
  pgdata: